In [21]:
# Разбираемся в библиотеках NumPy

In [ ]:
import numpy as np

In [11]:
a = np.array([[1, 2], [3, 3], [1, 6], [8, 11], [10, 7]])
mean_a = a.mean(axis = 0)
print(a, mean_a)

[[ 1  2]
 [ 3  3]
 [ 1  6]
 [ 8 11]
 [10  7]] [4.6 5.8]


In [12]:
a_centered = a - mean_a
print(a_centered)


[[-3.6 -3.8]
 [-1.6 -2.8]
 [-3.6  0.2]
 [ 3.4  5.2]
 [ 5.4  1.2]]


In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [20]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp = a_centered_sp / (a_centered.shape[0]-1)
print(a_centered_sp)

10.400000000000002
